
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:20}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:10}

spring.data.redis.lettuce.pool.max-active=${REDIS_POOL_MAX_ACTIVE:20}
spring.data.redis.lettuce.pool.max-idle=${REDIS_POOL_MAX_IDLE:20}
spring.data.redis.lettuce.pool.min-idle=${REDIS_POOL_MIN_IDLE:5}


server.forward-headers-strategy=framework
