-- src/main/resources/db/migration/V0__baseline_schema.sql
--
-- WHY THIS FILE EXISTS (read before touching it):
--
-- V1 through V13 all ALTER or reference tables such as users, projects,
-- categories, donations, reward_tiers, notifications, kyc_documents,
-- otp_verification, audit_logs, refresh_tokens, and the user_roles /
-- user_categories / project_categories collection tables -- but no migration
-- ever CREATEs them. They exist on every environment this project has run in
-- so far only because Hibernate's ddl-auto was set to `update` (or `create`)
-- long before Flyway was introduced, so it created them directly from the
-- JPA entities. Flyway was adopted later and only ever captured incremental
-- changes on top of that already-existing schema.
--
-- Confirmed directly: the flyway_schema_history table does not exist
-- anywhere in the current database dump (crowdspark.sql), and running V1
-- against a genuinely empty PostgreSQL database fails immediately with
-- "relation \"users\" does not exist". Flyway has never actually executed
-- against this project's database before now. On Render's managed
-- PostgreSQL -- which starts completely empty -- this migration chain would
-- fail on V1 on the very first deploy.
--
-- This migration creates exactly the tables/columns/constraints that V1-V13
-- assume already exist, reconstructed from the actual current schema dump,
-- MINUS whatever those later migrations add themselves (search_vector on
-- projects, totp fields on users, refresh token rotation columns, the
-- reward-tier quantity columns, and the DELETED account_status value) so
-- that V1-V13 still apply their own deltas on top without collisions.
--
-- Deliberately excluded (present in the dump, but not needed going forward):
--   - users_info / student_seq -- an abandoned early scaffold table+sequence
--     with no corresponding JPA entity; ddl-auto=validate never checks for
--     it, so nothing breaks by leaving it out of a fresh database.
--
-- Effect on the EXISTING database (this dev machine, staging, etc.): NONE.
-- spring.flyway.baseline-version is already 0, and Flyway skips any
-- migration whose version is <= the recorded baseline, so V0 is a no-op
-- everywhere that baseline has already run. It only does real work against
-- a schema that is completely empty (no flyway_schema_history table AND no
-- tables at all), which is exactly Render's fresh-database case and nothing
-- else -- baseline-on-migrate only triggers for a NON-empty unversioned
-- schema, so it is not involved here either way.

-- ============================================================
-- users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    about                   VARCHAR(1000),
    account_status          VARCHAR(255) NOT NULL,
    address_line            VARCHAR(255),
    banner_image_public_id  VARCHAR(255),
    banner_image_url        VARCHAR(255),
    bio                     VARCHAR(255),
    city                    VARCHAR(255),
    country                 VARCHAR(255),
    created_at              TIMESTAMP(6) NOT NULL,
    date_of_birth           DATE,
    email                   VARCHAR(255),
    email_verified          BOOLEAN NOT NULL,
    gender                  VARCHAR(255),
    instagram_url           VARCHAR(255),
    is_enabled              BOOLEAN NOT NULL,
    is_locked               BOOLEAN NOT NULL,
    kyc_status              VARCHAR(255) NOT NULL,
    last_login_at           TIMESTAMP(6),
    latitude                DOUBLE PRECISION,
    linkedin_url            VARCHAR(255),
    longitude               DOUBLE PRECISION,
    name                    VARCHAR(255),
    organization            VARCHAR(255),
    password                VARCHAR(255),
    phone_number            VARCHAR(255),
    phone_verified          BOOLEAN NOT NULL,
    pincode                 VARCHAR(255),
    place_id                VARCHAR(255),
    profession              VARCHAR(255),
    profile_image_public_id VARCHAR(255),
    profile_image_url       VARCHAR(255),
    provider                VARCHAR(255),
    provider_id             VARCHAR(255),
    state                   VARCHAR(255),
    total_amount_backed     DOUBLE PRECISION,
    total_funds_raised      DOUBLE PRECISION,
    total_projects_backed   INTEGER,
    total_projects_created  INTEGER,
    twitter_url             VARCHAR(255),
    username                VARCHAR(255),
    website_url             VARCHAR(255),
    bank_ifsc_code          VARCHAR(255),
    bank_name               VARCHAR(255),
    masked_bank_account     VARCHAR(255),
    upi_id                  VARCHAR(255),
    kyc_verified            BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number),
    CONSTRAINT uk_users_username UNIQUE (username),
    -- 'DELETED' is intentionally NOT included here -- V9 adds it via its own
    -- DROP+ADD, matching the pre-V9 state so that migration still does real work.
    CONSTRAINT users_account_status_check CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'BANNED')),
    CONSTRAINT users_gender_check CHECK (gender IN ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY')),
    CONSTRAINT users_kyc_status_check CHECK (kyc_status IN ('NOT_SUBMITTED', 'PENDING_SUBMISSION', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED'))
);

CREATE INDEX IF NOT EXISTS idx_users_account_status ON users (account_status);
CREATE INDEX IF NOT EXISTS idx_users_kyc_status ON users (kyc_status);

-- @ElementCollection tables on User (no PK/unique on either, matching the
-- current dump exactly -- Hibernate does not add one by default).
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role    VARCHAR(255),
    CONSTRAINT user_roles_role_check CHECK (role IN ('ADMIN', 'BACKER', 'CREATOR'))
);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles (user_id);

CREATE TABLE IF NOT EXISTS user_categories (
    user_id  BIGINT NOT NULL REFERENCES users(id),
    category VARCHAR(255)
);

-- ============================================================
-- categories
-- ============================================================
CREATE TABLE IF NOT EXISTS categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name)
);

-- ============================================================
-- projects
-- ============================================================
CREATE TABLE IF NOT EXISTS projects (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approved_at         TIMESTAMP(6),
    created_at          TIMESTAMP(6) NOT NULL,
    current_amount      DOUBLE PRECISION NOT NULL,
    deadline            TIMESTAMP(6) NOT NULL,
    full_description    VARCHAR(10000) NOT NULL,
    goal_amount         DOUBLE PRECISION NOT NULL,
    location            VARCHAR(255) NOT NULL,
    rejection_reason    VARCHAR(255),
    short_description   VARCHAR(300) NOT NULL,
    status              VARCHAR(255) NOT NULL,
    title               VARCHAR(255) NOT NULL,
    creator_id          BIGINT NOT NULL REFERENCES users(id),
    -- search_vector is deliberately NOT created here -- V3 adds the column,
    -- the trigger, and the trigger function together as one unit.
    CONSTRAINT projects_status_check CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'CLOSED', 'REJECTED', 'FUNDED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_projects_status_created_at ON projects (status, created_at);
CREATE INDEX IF NOT EXISTS idx_projects_title_lower ON projects (lower(title) text_pattern_ops);

CREATE TABLE IF NOT EXISTS project_categories (
    project_id  BIGINT NOT NULL REFERENCES projects(id),
    category_id BIGINT NOT NULL REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS project_media (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_order INTEGER,
    media_type    VARCHAR(255) NOT NULL,
    media_url     VARCHAR(255) NOT NULL,
    usage         VARCHAR(255) NOT NULL,
    project_id    BIGINT NOT NULL REFERENCES projects(id),
    CONSTRAINT project_media_media_type_check CHECK (media_type IN ('IMAGE', 'VIDEO')),
    CONSTRAINT project_media_usage_check CHECK (usage IN ('THUMBNAIL', 'CARD_VIDEO', 'GALLERY_IMAGE', 'STORY_IMAGE', 'MAIN_VIDEO'))
);

-- ============================================================
-- reward_tiers (V6/V11 create reward_claims on top of this; V12 adds the
-- quantity/delivery columns -- deliberately excluded here)
-- ============================================================
CREATE TABLE IF NOT EXISTS reward_tiers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description    VARCHAR(1000),
    minimum_amount DOUBLE PRECISION NOT NULL,
    title          VARCHAR(255) NOT NULL,
    project_id     BIGINT NOT NULL REFERENCES projects(id)
);

-- ============================================================
-- donations
-- ============================================================
CREATE TABLE IF NOT EXISTS donations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount              DOUBLE PRECISION NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL,
    message             VARCHAR(500),
    paid_at             TIMESTAMP(6),
    payment_status      VARCHAR(255) NOT NULL,
    transaction_id      VARCHAR(255),
    user_id             BIGINT NOT NULL REFERENCES users(id),
    project_id          BIGINT NOT NULL REFERENCES projects(id),
    reward_tier_id      BIGINT REFERENCES reward_tiers(id),
    razorpay_order_id   VARCHAR(255),
    refund_status       VARCHAR(30),
    refunded_at         TIMESTAMP,
    razorpay_refund_id  VARCHAR(255),
    CONSTRAINT donations_payment_status_check CHECK (payment_status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE INDEX IF NOT EXISTS idx_donations_razorpay_order_id ON donations (razorpay_order_id);

-- ============================================================
-- refresh_tokens (V7 adds family_id / parent_token_hash / created_at --
-- deliberately excluded here)
-- ============================================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP(6) NOT NULL,
    revoked     BOOLEAN NOT NULL,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT NOT NULL,
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token)
);

-- ============================================================
-- kyc_documents (no FK constraints in the live schema either -- matched
-- faithfully rather than adding integrity Hibernate never asked for)
-- ============================================================
CREATE TABLE IF NOT EXISTS kyc_documents (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aadhaar_back_image_url   VARCHAR(255),
    aadhaar_back_public_id   VARCHAR(255),
    aadhaar_front_image_url  VARCHAR(255),
    aadhaar_front_public_id  VARCHAR(255),
    aadhaar_number            VARCHAR(255),
    bank_account_holder_name VARCHAR(255),
    bank_account_number       VARCHAR(255),
    bank_branch_name          VARCHAR(255),
    bank_ifsc_code            VARCHAR(255),
    bank_name                 VARCHAR(255),
    kyc_status                VARCHAR(255) NOT NULL,
    pan_card_image_public_id VARCHAR(255),
    pan_card_image_url        VARCHAR(255),
    pan_number                 VARCHAR(255),
    rejection_reason           VARCHAR(255),
    reviewed_at                TIMESTAMP(6),
    reviewed_by_admin_id       BIGINT,
    submitted_at                TIMESTAMP(6) NOT NULL,
    upi_id                      VARCHAR(255),
    user_id                     BIGINT NOT NULL,
    CONSTRAINT uk_kyc_documents_user_id UNIQUE (user_id),
    CONSTRAINT kyc_documents_kyc_status_check CHECK (kyc_status IN ('NOT_SUBMITTED', 'PENDING_SUBMISSION', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED'))
);

-- ============================================================
-- otp_verification
-- ============================================================
CREATE TABLE IF NOT EXISTS otp_verification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255),
    expiry_time TIMESTAMP(6),
    otp         VARCHAR(255)
);

-- ============================================================
-- notifications
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES users(id),
    type         VARCHAR(255) NOT NULL,
    title        VARCHAR(255) NOT NULL,
    message      VARCHAR(500) NOT NULL,
    link         VARCHAR(255),
    reference_id BIGINT,
    read         BOOLEAN DEFAULT FALSE NOT NULL,
    created_at   TIMESTAMP,
    read_at      TIMESTAMP,
    is_read      BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications (is_read);

-- ============================================================
-- audit_logs
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    entity_id   BIGINT,
    entity_type VARCHAR(255),
    user_id     BIGINT
);

-- ============================================================
-- user_rewards -- UserReward.java is a live @Entity (so ddl-auto=validate
-- checks for this table on every startup) even though nothing calls its
-- repository today. Must exist or the app fails to boot; not our call to
-- remove dead code as part of a deployment pass.
-- ============================================================
CREATE TABLE IF NOT EXISTS user_rewards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT,
    reward_id   BIGINT,
    user_id     BIGINT
);
