-- src/main/resources/db/migration/V15__project_fraud_checks.sql
-- Feature #43: AI Fraud & Risk Detection
-- One row per project, created/updated by the async fraud-scan worker that
-- runs on submission (see RedisQueueService "ai-fraud-scan" queue, and
-- FraudScanJobWorker). Guarded with IF NOT EXISTS throughout, matching every
-- migration since V6 — see V6's note for why (Hibernate ddl-auto=update
-- having created something with the same name outside Flyway is the
-- recurring reason this matters on this project).

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fraud_check_status') THEN
        CREATE TYPE fraud_check_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS project_fraud_checks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,

    status          fraud_check_status NOT NULL DEFAULT 'PENDING',
    risk_score      INTEGER,             -- 0-100, NULL until status = COMPLETED
    risk_level      VARCHAR(10),         -- LOW / MEDIUM / HIGH, NULL until COMPLETED
    reasoning       TEXT,
    signals         TEXT,                -- newline-separated specific flagged concerns

    model           VARCHAR(100),
    checked_at      TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fraud_checks_project_id ON project_fraud_checks (project_id);
CREATE INDEX IF NOT EXISTS idx_fraud_checks_risk_level ON project_fraud_checks (risk_level) WHERE risk_level IS NOT NULL;
