-- src/main/resources/db/migration/V16__kyc_document_ai_checks.sql
-- Feature #44: AI KYC Document Validation
-- One row per KYC submission, populated by the async vision-check worker
-- triggered when a creator submits KYC (see AiJobWorker's "SCAN_KYC_DOCUMENT"
-- job type). Guarded with IF NOT EXISTS throughout, matching every migration
-- since V6.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'kyc_check_status') THEN
        CREATE TYPE kyc_check_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS kyc_document_ai_checks (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kyc_document_id       BIGINT NOT NULL UNIQUE REFERENCES kyc_documents(id) ON DELETE CASCADE,

    status                kyc_check_status NOT NULL DEFAULT 'PENDING',
    readable              BOOLEAN,             -- NULL until status = COMPLETED
    tampering_suspected   BOOLEAN,             -- NULL until status = COMPLETED
    concerns              TEXT,                -- newline-separated; never the ID number/name/address/DOB itself
    summary               TEXT,

    model                 VARCHAR(100),
    checked_at            TIMESTAMP,
    created_at            TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kyc_ai_checks_kyc_document_id ON kyc_document_ai_checks (kyc_document_id);
