-- src/main/resources/db/migration/V17__content_moderation_checks.sql
-- Feature #45: AI Content Moderation
-- One row per (content_type, content_id) pair, covering both project
-- descriptions and comments. No FK on content_id since it points at
-- different tables depending on content_type -- see the entity-level
-- comment on ContentModerationCheck for the full reasoning. Guarded with
-- IF NOT EXISTS throughout, matching every migration since V6.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'content_type') THEN
        CREATE TYPE content_type AS ENUM ('PROJECT', 'COMMENT');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'moderation_status') THEN
        CREATE TYPE moderation_status AS ENUM ('PENDING', 'CLEAR', 'FLAGGED', 'FAILED');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS content_moderation_checks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type       content_type NOT NULL,
    content_id         BIGINT NOT NULL,

    status             moderation_status NOT NULL DEFAULT 'PENDING',
    category           VARCHAR(20),         -- spam / hate_speech / misleading / none
    reasoning          TEXT,

    model              VARCHAR(100),
    checked_at         TIMESTAMP,
    resolved_by_admin  BOOLEAN NOT NULL DEFAULT FALSE,

    created_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_moderation_content ON content_moderation_checks (content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_moderation_status  ON content_moderation_checks (status);
