-- src/main/resources/db/migration/V18__campaign_weekly_insights.sql
-- Feature #48: AI Creator Analytics Insights
-- One row per (project, week), written by the new weekly @Scheduled job
-- (CreatorInsightSchedulerService). No FK cascade needed beyond the
-- standard project_id reference; guarded with IF NOT EXISTS throughout,
-- matching every migration since V6.

CREATE TABLE IF NOT EXISTS campaign_weekly_insights (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id             BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,

    week_start             DATE NOT NULL,
    summary_text           TEXT NOT NULL,

    views_this_week        INTEGER NOT NULL DEFAULT 0,
    new_backers_this_week  INTEGER NOT NULL DEFAULT 0,
    funded_percent         INTEGER NOT NULL DEFAULT 0,

    model                  VARCHAR(100),
    generated_at           TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_weekly_insights_project_id ON campaign_weekly_insights (project_id, week_start);
