-- src/main/resources/db/migration/V2__features_5_7_payouts_refunds.sql
-- Covers tables introduced in Features #3, #4, #5, #6, #7
-- (campaign_updates, project_comments, saved_projects, payouts, refunds)
--
-- NOTE: These tables exist in the production DB SQL dump but were never
-- codified as Flyway migrations. This file makes fresh deployments
-- (e.g. Docker) create them correctly via the Flyway lifecycle.

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #5 — Creator Campaign Updates
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS campaign_updates (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    author_id  BIGINT        NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    title      VARCHAR(255)  NOT NULL,
    content    TEXT          NOT NULL,
    image_url  VARCHAR(500),
    created_at TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_campaign_updates_project_id
    ON campaign_updates (project_id, created_at DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #6 — Comments & Backer–Creator Q&A
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS project_comments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT   NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    author_id         BIGINT   NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    parent_comment_id BIGINT   REFERENCES project_comments(id)  ON DELETE CASCADE,
    content           TEXT     NOT NULL,
    deleted           BOOLEAN  NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_project_comments_project_id
    ON project_comments (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_comments_parent_id
    ON project_comments (parent_comment_id);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #7 — Save / Watchlist
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS saved_projects (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    project_id BIGINT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    saved_at   TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_saved_project UNIQUE (user_id, project_id)
);

CREATE INDEX IF NOT EXISTS idx_saved_projects_user_id
    ON saved_projects (user_id, saved_at DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #3 — Creator Payout / Fund Disbursement
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS payouts (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id               BIGINT         NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    creator_id               BIGINT         NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
    gross_amount             DOUBLE PRECISION NOT NULL,
    platform_fee_percent     DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    platform_fee_amount      DOUBLE PRECISION NOT NULL,
    net_amount               DOUBLE PRECISION NOT NULL,
    status                   VARCHAR(30)    NOT NULL DEFAULT 'INITIATED',
    payout_mode              VARCHAR(20)    NOT NULL DEFAULT 'UPI',
    upi_id_snapshot          VARCHAR(255),
    razorpay_contact_id      VARCHAR(255),
    razorpay_fund_account_id VARCHAR(255),
    razorpay_payout_id       VARCHAR(255),
    failure_reason           TEXT,
    initiated_by_id          BIGINT         REFERENCES users(id) ON DELETE SET NULL,
    initiated_at             TIMESTAMP      NOT NULL DEFAULT NOW(),
    completed_at             TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payouts_project_id  ON payouts (project_id);
CREATE INDEX IF NOT EXISTS idx_payouts_creator_id  ON payouts (creator_id);
CREATE INDEX IF NOT EXISTS idx_payouts_status      ON payouts (status);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #4 — Refund Handling for Failed Campaigns
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS refunds (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id       BIGINT           NOT NULL REFERENCES donations(id) ON DELETE RESTRICT,
    backer_id         BIGINT           NOT NULL REFERENCES users(id)     ON DELETE RESTRICT,
    project_id        BIGINT           NOT NULL REFERENCES projects(id)  ON DELETE RESTRICT,
    amount            DOUBLE PRECISION NOT NULL,
    status            VARCHAR(30)      NOT NULL DEFAULT 'INITIATED',
    razorpay_refund_id VARCHAR(255),
    failure_reason    TEXT,
    initiated_at      TIMESTAMP        NOT NULL DEFAULT NOW(),
    completed_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_refunds_donation_id  ON refunds (donation_id);
CREATE INDEX IF NOT EXISTS idx_refunds_project_id   ON refunds (project_id);
CREATE INDEX IF NOT EXISTS idx_refunds_backer_id    ON refunds (backer_id);
CREATE INDEX IF NOT EXISTS idx_refunds_status       ON refunds (project_id, status);
