-- src/main/resources/db/migration/V3__features_15_to_22.sql
-- Covers tables and schema changes introduced in Features #15–22
-- (project_views, user_follows, project_reviews, project_milestones, fcm_tokens,
--  search_vector column + trigger on projects)
--
-- These tables existed only in the SQL dump. This migration ensures they are
-- created on every fresh deployment (Docker, CI/CD, staging, new dev machine).

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #17 — Creator Analytics: project view counters
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS project_views (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    view_date    DATE   NOT NULL DEFAULT CURRENT_DATE,
    view_count   BIGINT NOT NULL DEFAULT 0,
    unique_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_project_views_project_date UNIQUE (project_id, view_date)
);

CREATE INDEX IF NOT EXISTS idx_project_views_project_id
    ON project_views (project_id, view_date DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #18 — User Follow / Social Graph
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_follows (
    id           BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id  BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    following_id BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    followed_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_follow           UNIQUE (follower_id, following_id),
    CONSTRAINT chk_no_self_follow  CHECK  (follower_id <> following_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_follower_id
    ON user_follows (follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following_id
    ON user_follows (following_id);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #19 — Project Reviews & Ratings
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS project_reviews (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    reviewer_id BIGINT    NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    rating      INTEGER   NOT NULL CHECK (rating BETWEEN 1 AND 5),
    title       VARCHAR(255),
    content     TEXT,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP,
    CONSTRAINT uq_review_user_project UNIQUE (project_id, reviewer_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_project_id
    ON project_reviews (project_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer_id
    ON project_reviews (reviewer_id);
CREATE INDEX IF NOT EXISTS idx_reviews_rating
    ON project_reviews (project_id, rating);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #20 — Project Milestones Tracking
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS project_milestones (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title         VARCHAR(255) NOT NULL,
    description   TEXT,
    target_amount DOUBLE PRECISION,
    sort_order    INTEGER   NOT NULL DEFAULT 0,
    completed_at  TIMESTAMP,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_milestones_project_id
    ON project_milestones (project_id);
CREATE INDEX IF NOT EXISTS idx_milestones_project_order
    ON project_milestones (project_id, sort_order);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #22 — Web Push Notifications (FCM tokens)
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fcm_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token        TEXT         NOT NULL,
    device_hint  VARCHAR(100),
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMP,
    CONSTRAINT uq_fcm_token UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS idx_fcm_tokens_user_id
    ON fcm_tokens (user_id);

-- ────────────────────────────────────────────────────────────────────────────
-- Feature #16 — Full-Text Search: search_vector column on projects
-- ────────────────────────────────────────────────────────────────────────────

-- 1. Add the tsvector column (IF NOT EXISTS = safe to re-run)
ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS search_vector tsvector;

-- 2. Create GIN index for fast full-text queries
CREATE INDEX IF NOT EXISTS idx_projects_search_vector
    ON projects USING GIN (search_vector);

-- 3. Trigger function — keeps search_vector in sync automatically
CREATE OR REPLACE FUNCTION update_project_search_vector()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', COALESCE(NEW.title, '')),            'A') ||
        setweight(to_tsvector('english', COALESCE(NEW.short_description, '')), 'B') ||
        setweight(to_tsvector('english', COALESCE(NEW.full_description, '')),  'C') ||
        setweight(to_tsvector('english', COALESCE(NEW.location, '')),          'D');
    RETURN NEW;
END;
$$;

-- 4. Attach trigger (DROP first so re-running the migration is safe)
DROP TRIGGER IF EXISTS trg_project_search_vector ON projects;

CREATE TRIGGER trg_project_search_vector
    BEFORE INSERT OR UPDATE OF title, short_description, full_description, location
    ON projects
    FOR EACH ROW EXECUTE FUNCTION update_project_search_vector();

-- 5. Back-fill existing rows so search works immediately after migration
UPDATE projects
SET search_vector =
    setweight(to_tsvector('english', COALESCE(title, '')),            'A') ||
    setweight(to_tsvector('english', COALESCE(short_description, '')), 'B') ||
    setweight(to_tsvector('english', COALESCE(full_description, '')),  'C') ||
    setweight(to_tsvector('english', COALESCE(location, '')),          'D')
WHERE search_vector IS NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- Performance indexes missed in original schema (Feature #33 partial)
-- ────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_donations_project_id
    ON donations (project_id);
-- AUDIT FIX: this referenced notifications.user_id, which does not exist —
-- the FK column on this table is actually named recipient_id (see the
-- Notification entity's @JoinColumn). Postgres throws
-- "column \"user_id\" does not exist" here, which aborts this migration's
-- transaction and blocks every migration after it (V4-V13 never run) on
-- ANY fresh database — Docker, CI, or a new dev machine. Fixed to the real
-- column name and given a name that matches it.
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_id
    ON notifications (recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_media_project_id
    ON project_media (project_id);
CREATE INDEX IF NOT EXISTS idx_projects_creator_id
    ON projects (creator_id);
CREATE INDEX IF NOT EXISTS idx_projects_status_created
    ON projects (status, created_at DESC);
