-- src/main/resources/db/migration/V6__reward_claims.sql
-- Feature #24: Reward Tier Claiming & Fulfillment
-- Tracks per-donation reward fulfillment status.
-- A claim is created automatically when a donation with a reward_tier_id
-- transitions to PaymentStatus = SUCCESS.

-- AUDIT FIX: Postgres has no "CREATE TYPE IF NOT EXISTS" syntax, so this is
-- guarded with a DO block instead. Needed because on a database where
-- reward_claims was already created some other way (e.g. Hibernate
-- ddl-auto=update during earlier development, before Flyway took over
-- schema ownership), this type wouldn't exist yet even though the table
-- does — running the migration must not blow up in that situation.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reward_claim_status') THEN
        CREATE TYPE reward_claim_status AS ENUM (
            'PENDING',      -- donation confirmed, creator hasn't started yet
            'PROCESSING',   -- creator acknowledged and is working on it
            'SHIPPED',      -- physical reward dispatched (tracking number set)
            'FULFILLED',    -- reward delivered / digital reward sent
            'CANCELLED'     -- donation was refunded; reward no longer owed
        );
    END IF;
END $$;

-- AUDIT FIX: was CREATE TABLE with no guard, which fails with
-- "relation reward_claims already exists" on any database where this table
-- was already created outside this exact migration (see note above) — the
-- most common way to reach that state. IF NOT EXISTS makes this a safe
-- no-op there while still creating the table fresh from scratch elsewhere.
CREATE TABLE IF NOT EXISTS reward_claims (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id       BIGINT        NOT NULL UNIQUE REFERENCES donations(id) ON DELETE CASCADE,
    backer_id         BIGINT        NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    reward_tier_id    BIGINT        NOT NULL REFERENCES reward_tiers(id) ON DELETE CASCADE,
    project_id        BIGINT        NOT NULL REFERENCES projects(id)  ON DELETE CASCADE,

    status            reward_claim_status NOT NULL DEFAULT 'PENDING',

    -- Backer-supplied delivery details (for physical rewards)
    shipping_name     VARCHAR(255),
    shipping_address  TEXT,
    shipping_city     VARCHAR(100),
    shipping_pincode  VARCHAR(20),
    shipping_country  VARCHAR(100) DEFAULT 'India',
    shipping_phone    VARCHAR(20),

    -- Creator-supplied fulfillment details
    tracking_number   VARCHAR(255),
    fulfillment_note  TEXT,

    claimed_at        TIMESTAMP NOT NULL DEFAULT NOW(),
    fulfilled_at      TIMESTAMP
);

-- AUDIT FIX: added IF NOT EXISTS to all four — same reasoning as the table
-- above; these already exist on a database where reward_claims was created
-- outside this migration, and CREATE INDEX with no guard fails hard on a
-- name that's already taken.
CREATE INDEX IF NOT EXISTS idx_reward_claims_backer_id    ON reward_claims (backer_id);
CREATE INDEX IF NOT EXISTS idx_reward_claims_project_id   ON reward_claims (project_id);
CREATE INDEX IF NOT EXISTS idx_reward_claims_tier_id      ON reward_claims (reward_tier_id);
CREATE INDEX IF NOT EXISTS idx_reward_claims_status       ON reward_claims (project_id, status);
